project:
  type: website
  output-dir: docs

website:
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Temoor Tayyab, University of Toronto @ 2024"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Projects
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css

editor: visual

execute:
  freeze: auto # re-render only when source changes
  
  